version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: cinemadb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - network
    expose:
      - "5432"

  service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinema-service
    networks:
      - network
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cinemadb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword

networks:
  network:
    driver: bridge